name: flutter_pipeline
description: A flutter plugin to record crashes compatible with FCR and all real time crash reporting tool too.
version: 0.0.2
homepage: https://github.com/raj457036/flutter_crash_recorder/tree/main/flutter_pipeline
repository: https://github.com/raj457036/flutter_crash_recorder

environment:
  sdk: '>=2.19.3 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  universal_io: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter: