name: flutter_local_crash_recorder
description: A crash local recorder server for flutter pipeline plugin
version: 1.0.0
# repository: https://github.com/my_org/my_repo

executables:
  fcr:  server

environment:
  sdk: '>=2.16.1 <3.0.0'

dependencies:
  args: ^2.3.1
  shelf: ^1.3.2
  shelf_router: ^1.1.3
  path: ^1.8.3

dev_dependencies:
  http: ^0.13.5
  lints: ^1.0.1
  test:
